spring:
  application:
    name: feedgram-discovery

server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

#VYSVETLENI
#  register-with-eureka
#  - slouzi k tomu, zda client sam sebe zaregistruje a tim se stane "objevitelnym"
#  - to samo o sobe ale neznamena, ze tento klient bude ziskavat informace o end-pointech jinych sluzeb a tim padem ze se k nim bude moct pripojit
#
#  fetch-registry
#  - slouzi k tomu, zda se client pripoji k serverum Eureka, aby mohla stahovat informace o dalsich end-pointech. Muze tak ucinit, aniz by se zaregistroval
#
# Defaultni hodnota obou je true, my nastavujeme nyní na false, protoze jsme discovery service a nechceme, aby sebe sama registrovala.